---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        enable_grpc_web: True
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: ambassador-consul
      hosts: []
      secret: ambassador-consul-connect
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - name: http
     port: 80
     targetPort: 80
   - name: https
     port: 443
     targetPort: 443
  selector:
    service: ambassador
