---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8443
        enable_grpc_web: true
        default_label_domain: ambassador
        default_labels:
          ambassador:
            defaults:
            - x_limited_user:
                header: "x-limited-user"
                omit_if_not_present: true
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: ambassador-consul
      hosts: []
      secret: ambassador-consul-connect
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
          alpn_protocols: h2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - name: http
     port: 80
     targetPort: 8080
   - name: https
     port: 443
     targetPort: 8443
  selector:
    service: ambassador
