---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: httpbin
spec:
  prefix: /httpbin/
  service: httpbin.org:80
  host_rewrite: httpbin.org
  labels:
    ambassador:
      - request_label_group:
        - remote_address
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: httpbin-limited
spec:
  prefix: /httpbin-limited/
  service: httpbin.org:80
  host_rewrite: httpbin.org
