---
apiVersion: v1
kind: Service
metadata:
  name: qotm-consul
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  qotm_consul_mapping
      prefix: /qotm/
      tls: ambassador-consul
      service: https://qotm-consul:443
spec:
  type: NodePort
  selector:
    app: qotm-consul
  ports:
  - port: 443
    name: https-qotm
    targetPort: 20000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qotm-consul
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm-consul
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.4
        ports:
        - name: http-api
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi