---
apiVersion: v1
kind: Service
metadata:
  name: routing
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org   
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  httpbin_mapping_keycloak
      prefix: /keycloak/httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
      timeout_ms: 5000
spec:
  ports:
  - name: httpbin
    port: 80
