apiVersion: getambassador.io/v1beta1
kind: RateLimit
metadata:
  name: per-user-rate-limit
spec:
  domain: ambassador
  limits:
   - pattern: [{x_limited_user: "false"}, {remote_address: "*"}]
     rate: 20
     unit: minute